<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.75.1" />


<title>Opinion towards Liberal and gender - A Hugo website</title>
<meta property="og:title" content="Opinion towards Liberal and gender - A Hugo website">


  <link href='../../../../favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="../../../../css/fonts.css" media="all">
<link rel="stylesheet" href="../../../../css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="../../../../" class="nav-logo">
    <img src="../../../../images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="../../../../about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/rstudio">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">10 min read</span>
    

    <h1 class="article-title">Opinion towards Liberal and gender</h1>

    
    <span class="article-date">2015-07-23</span>
    

    <div class="article-content">
      


<div id="abstract" class="section level1">
<h1>Abstract</h1>
<p>“In this paper we analysed the 2019 CES phone survey data. By analyzing the data, the results showed that females have more positive opinion towards Liberal in Canada. These results are important because it gives a forecast people’s behavior in the election and can give a positive impact on the party’s campaign strategy.”</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In Canada, the difference political opinion among genders have been extended in the last election. It might be a dangerous signal that after the race, each gender may have their own “identity politics”. Thus, by analyzing the opinions in each genders towards Liberal we can have a glance at the situation. We find that the female hold a more positive opinion towards Liberal.</p>
<p>In our study, we analyzed the data from the 2019 CES phone survey, we try to find the relationship between each individuals opinion towards Liberal(a numeric score) and gender(male, female and others), we find that there exist a significant difference on their attitudes. On a scale of 0-100, the median score female respondents give is 60 which male respondents give is only 50.</p>
<p>We analyzed the different popularity of Liberal in each gender. However we may ignore some other facts that also influence people’s choices, for example income, since Liberal party may give higher tax rate for high-income groups. For further study we can focus on these factors which may also influence people’s attitudes and opinions in the election and not only limitted to gender.</p>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>The 2019 Canadian Election Study - Phone Survey gathered the attitudes and opinions of Canadians during and after the 2019 federal election, and used to study the reasons of peoples’ choice. It widely assemble Canadians’ attitudes on the social issues, economics and political opinions. The 2019 CES phone survey dataset contains the data from the result of the phone survey of 2019 Canadian Election.</p>
<pre class="r"><code>#install.packages(&quot;devtools&quot;)
library(devtools)</code></pre>
<pre><code>## Loading required package: usethis</code></pre>
<pre class="r"><code>devtools::install_github(&quot;hodgettsp/cesR&quot;)</code></pre>
<pre><code>## Skipping install of &#39;cesR&#39; from a github remote, the SHA1 (7c780beb) has not changed since last install.
##   Use `force = TRUE` to force installation</code></pre>
<pre class="r"><code>library(cesR)
get_ces(&quot;ces2019_phone&quot;)</code></pre>
<pre><code>## TO CITE THIS SURVEY FILE:
## 
## - Stephenson, Laura B; Harell, Allison; Rubenson, Daniel; Loewen, Peter John, 2020, &#39;2019 Canadian Election Study - Phone Survey&#39;, https://doi.org/10.7910/DVN/8RHLG1, Harvard Dataverse, V1, UNF:6:eyR28qaoYlHj9qwPWZmmVQ== [fileUNF]
## 
## - Stephenson, Laura, Allison Harrel, Daniel Rubenson and Peter Loewen. Forthcoming. &#39;Measuring Preferences and Behaviour in the 2019 Canadian Election Study,&#39; Canadian Journal of Political Science.
## 
## LINK: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/8RHLG1</code></pre>
<pre class="r"><code>data &lt;- ces2019_phone</code></pre>
<p>We mainly focus on some of the variables that are listed in the table below:</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>selected_data &lt;- data %&gt;% select(sample_id, q2, q3, q9, q14, q15, q16, q61, q69)
colnames(selected_data) &lt;- c(&quot;id&quot;, &quot;year_of_born&quot;, &quot;gender&quot;, &quot;how_interesting_in_election&quot;, &quot;opinion_towards_Liberal&quot;, &quot;opinion towards Conservative&quot;, &quot;opinion towards NDP&quot;, &quot;education&quot;, &quot;household_income&quot; )
data_description &lt;- data.frame(CES_names=c(&quot;sample_id&quot;, &quot;q2&quot;, &quot;q3&quot;, &quot;q9&quot;, &quot;q14&quot;, &quot;q15&quot;, &quot;q16&quot;, &quot;q61&quot;, &quot;q69&quot;),variable_descriptions=c(&quot;id&quot;, &quot;year of born&quot;, &quot;gender&quot;, &quot;how interesting in election?&quot;, &quot;opinion towards Liberal&quot;, &quot;opinion towards Conservative&quot;, &quot;opinion towards NDP&quot;, &quot;education&quot;, &quot;household income&quot;))
data_description</code></pre>
<pre><code>##   CES_names        variable_descriptions
## 1 sample_id                           id
## 2        q2                 year of born
## 3        q3                       gender
## 4        q9 how interesting in election?
## 5       q14      opinion towards Liberal
## 6       q15 opinion towards Conservative
## 7       q16          opinion towards NDP
## 8       q61                    education
## 9       q69             household income</code></pre>
<p>We can see that how interesting in election, opinion towards Liberal, Conservative and NDP are represented by the number, higher number means more positive, lower number means more negative. And negative number means that the respondents don’t know the answer or chose not to answer which should be treated like missing values. Thus we need to replace that negative values with NA.</p>
<pre class="r"><code>selected_data[selected_data==-9] &lt;- NA
selected_data[selected_data==-8] &lt;- NA
selected_data[selected_data==-6] &lt;- NA
selected_data</code></pre>
<pre><code>## # A tibble: 4,021 x 9
##       id year_of_born  gender how_interesting… opinion_towards… `opinion toward…
##    &lt;dbl&gt;    &lt;dbl+lbl&gt; &lt;dbl+l&gt;        &lt;dbl+lbl&gt;        &lt;dbl+lbl&gt;        &lt;dbl+lbl&gt;
##  1    18         1963 1 [(1)…  8 [(8)]                       60               40
##  2    32         1973 1 [(1)… 10 [(10) Great …               70               55
##  3    39         1994 1 [(1)… 10 [(10) Great …               70               60
##  4    59         2000 1 [(1)…  6 [(6)]                       75               40
##  5    61         1984 1 [(1)… 10 [(10) Great …               10               10
##  6    69         1939 1 [(1)… 10 [(10) Great …                0               30
##  7   157         1999 1 [(1)…  6 [(6)]                       50               20
##  8   158         1995 1 [(1)…  8 [(8)]                       65               25
##  9   165         1963 1 [(1)…  7 [(7)]                       50               80
## 10   167         1970 1 [(1)…  7 [(7)]                       70               10
## # … with 4,011 more rows, and 3 more variables: `opinion towards
## #   NDP` &lt;dbl+lbl&gt;, education &lt;dbl+lbl&gt;, household_income &lt;dbl+lbl&gt;</code></pre>
<p>The following graph showing the type of each variables,and it also shows the distribution of the missing values in order to avoid that the missing value influence the result.</p>
<pre class="r"><code>#install.packages(&quot;visdat&quot;)
library(visdat)
visdat::vis_dat(selected_data) </code></pre>
<p><img src="../../../../post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>summary(selected_data)</code></pre>
<pre><code>##        id          year_of_born      gender      how_interesting_in_election
##  Min.   :    18   Min.   :1919   Min.   :1.000   Min.   : 0.000             
##  1st Qu.: 24354   1st Qu.:1955   1st Qu.:1.000   1st Qu.: 6.000             
##  Median : 66854   Median :1968   Median :1.000   Median : 8.000             
##  Mean   : 59991   Mean   :1968   Mean   :1.435   Mean   : 7.431             
##  3rd Qu.: 92449   3rd Qu.:1981   3rd Qu.:2.000   3rd Qu.:10.000             
##  Max.   :117856   Max.   :2001   Max.   :3.000   Max.   :10.000             
##                                                  NA&#39;s   :9                  
##  opinion_towards_Liberal opinion towards Conservative opinion towards NDP
##  Min.   :  0.0           Min.   :  0.00               Min.   :  0.00     
##  1st Qu.: 20.0           1st Qu.: 20.00               1st Qu.: 25.00     
##  Median : 50.0           Median : 45.00               Median : 50.00     
##  Mean   : 47.5           Mean   : 43.27               Mean   : 45.49     
##  3rd Qu.: 70.0           3rd Qu.: 69.50               3rd Qu.: 70.00     
##  Max.   :100.0           Max.   :100.00               Max.   :100.00     
##  NA&#39;s   :82              NA&#39;s   :110                  NA&#39;s   :165        
##    education      household_income 
##  Min.   : 1.000   Min.   :      0  
##  1st Qu.: 6.000   1st Qu.:  45000  
##  Median : 8.000   Median :  80000  
##  Mean   : 7.607   Mean   : 105046  
##  3rd Qu.: 9.000   3rd Qu.: 140000  
##  Max.   :11.000   Max.   :2120000  
##  NA&#39;s   :11       NA&#39;s   :946</code></pre>
<p>We can see there are 9 variables and 4021 observations, there exists a few missing values in opinions towards parties and house hold income.</p>
<pre class="r"><code>install.packages(&quot;tidyverse&quot;)</code></pre>
<pre><code>## Installing package into &#39;/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0&#39;
## (as &#39;lib&#39; is unspecified)</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.3     ✓ stringr 1.4.0
## ✓ tidyr   1.1.2     ✓ forcats 0.5.0
## ✓ readr   1.3.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>selected_data %&gt;% 
  ggplot(aes(x = household_income)) +
  geom_bar(col=&quot;blue&quot;)  +
  labs(title=&quot;Household income barplot&quot;, 
       caption = &quot;Data source: the dataset is from 2019 CES dataset&quot;)</code></pre>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
<pre><code>## Warning: Removed 946 rows containing non-finite values (stat_count).</code></pre>
<p><img src="../../../../post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>summary(selected_data$household_income)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##       0   45000   80000  105046  140000 2120000     946</code></pre>
<p>From the household income data we know that the 1st Quartile is 45000, the Median household income is 80000, the 3rd Quantile is 140000. 946 out of 4021 people’s household income data are unavailable.</p>
<pre class="r"><code>sexuality_num = table(selected_data$gender)
sexuality_prob = round(prop.table(table(selected_data$gender)), 3)
sexuality_summary &lt;- data.frame(gender = c(&quot;male&quot;, &quot;female&quot;, &quot;other&quot;), sexuality_num , sexuality_prob)
sexuality_summary</code></pre>
<pre><code>##   gender Var1 Freq Var1.1 Freq.1
## 1   male    1 2272      1  0.565
## 2 female    2 1748      2  0.435
## 3  other    3    1      3  0.000</code></pre>
<p>From the sexuality data we know that 56.5% of the respondents are male, 43.5% of the respondents are female and the other 1 people choose the other sexuality.</p>
<p>#Graph</p>
<pre class="r"><code>selected_data$gender &lt;- as.character(selected_data$gender)
ggplot(selected_data, aes(x=gender, y=opinion_towards_Liberal)) + 
  geom_boxplot() + theme_bw() + 
  labs(title=&quot;Box plot of opinion towards Liberal and gender&quot;, x=&quot;gender&quot;, y=&quot;income&quot;,
       caption = &quot;Data source: the dataset is from 2019 CES dataset&quot;)</code></pre>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
<pre><code>## Warning: Removed 82 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="../../../../post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>opinion_towards_Liberal_gender &lt;- selected_data %&gt;% select(opinion_towards_Liberal, gender)
opinion_towards_Liberal_gender &lt;- na.omit(opinion_towards_Liberal_gender) 

opinion_towards_Liberal_gender_summary &lt;- opinion_towards_Liberal_gender %&gt;% group_by(gender) %&gt;% summarise(maximum = max(opinion_towards_Liberal), minimum = min(opinion_towards_Liberal), median = median(opinion_towards_Liberal), mean = mean(opinion_towards_Liberal), variance= var(opinion_towards_Liberal), standard_deviation = sd(opinion_towards_Liberal))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code>opinion_towards_Liberal_gender_summary</code></pre>
<pre><code>## # A tibble: 3 x 7
##   gender   maximum   minimum median  mean variance standard_deviation
##   &lt;chr&gt;  &lt;dbl+lbl&gt; &lt;dbl+lbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;              &lt;dbl&gt;
## 1 1            100         0     50  44.3     852.               29.2
## 2 2            100         0     60  51.8     817.               28.6
## 3 3             40        40     40  40        NA                NA</code></pre>
<pre class="r"><code>opinion_towards_Liberal_gender = opinion_towards_Liberal_gender[opinion_towards_Liberal_gender$gender != 3,]
t.test(opinion_towards_Liberal_gender$opinion_towards_Liberal~opinion_towards_Liberal_gender$gender)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  opinion_towards_Liberal_gender$opinion_towards_Liberal by opinion_towards_Liberal_gender$gender
## t = -8.1045, df = 3696, p-value = 7.132e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -9.340696 -5.701686
## sample estimates:
## mean in group 1 mean in group 2 
##        44.25469        51.77588</code></pre>
<p>Since there is only 1 data of the third sexuality, it will not influence the result significantly, thus in order to do a T-test we only considering male and female. The p-value is smaller than 0.05 thus we have strong evidence against the null hypothesis.</p>
</div>
<div id="graph-discussion" class="section level1">
<h1>Graph Discussion</h1>
<p>From the summary we can see the difference attitude towards Liberal on each gender.Even though both male and female have great supporters (who gives score of 100) and Opponents (who gives score of 0), but female’s median and mean is much higher compare to male. Also, female’s income have smaller variance and standard deviation, which means within the same gender, the opinion difference is smaller in female compare to male.</p>
<p>Thus we may say that Liberal’s popularity is different in different gender.</p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>By analyzing the data for the 2019 CES phone survey data we can notice a significant different opinion towards Liberal in male and female. Liberal have more popularity among female which manifest as more positive rate. The box plot of gender and opinions and the data group by gender can support the conclusion. Also, the p-value from the t-test give us strong evidence support our conclusion. In order to do a t-test, we ignore the genders other than male and female, in our sample there is only one data have been ignore but we might need another statistical analysis method for more accurate analyze.</p>
</div>
<div id="weakness-and-next-steps" class="section level1">
<h1>Weakness and Next Steps</h1>
<p>There exist some of missing values which we chose to ignore, it might cause a biased result. Also, there exists some other factors that might impact people’s opinions towards Liberal like income. We can not get a direct causal relationship between gender and opinion towards Liberal.</p>
<p>In the further study we can try to get more detailed data to avoid missing values and investigate the relationship between each genders’ income and their opinion towards Liberal, other factors may also be considered. Then we can have a more accurate results.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<ul>
<li><p>Stephenson, Laura B; Harell, Allison; Rubenson, Daniel; Loewen, Peter John, 2020, ‘2019 Canadian Election Study - Phone Survey’, <a href="https://doi.org/10.7910/DVN/8RHLG1" class="uri">https://doi.org/10.7910/DVN/8RHLG1</a>, Harvard Dataverse, V1, UNF:6:eyR28qaoYlHj9qwPWZmmVQ== [fileUNF]</p></li>
<li><p>Stephenson, Laura, Allison Harrel, Daniel Rubenson and Peter Loewen. Forthcoming. ‘Measuring Preferences and Behaviour in the 2019 Canadian Election Study,’ Canadian Journal of Political Science.</p></li>
</ul>
<p>LINK: <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/8RHLG1" class="uri">https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/8RHLG1</a></p>
<p>Hadley Wickham, Jim Hester and Winston Chang (2020). devtools: Tools to
Make Developing R Packages Easier. <a href="https://devtools.r-lib.org/" class="uri">https://devtools.r-lib.org/</a>,
<a href="https://github.com/r-lib/devtools" class="uri">https://github.com/r-lib/devtools</a>.</p>
<p>Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2020).
dplyr: A Grammar of Data Manipulation. <a href="https://dplyr.tidyverse.org" class="uri">https://dplyr.tidyverse.org</a>,
<a href="https://github.com/tidyverse/dplyr" class="uri">https://github.com/tidyverse/dplyr</a>.</p>
<p>Tierney N (2017). “visdat: Visualising Whole Data Frames.” <em>JOSS</em>, <em>2</em>(16),
355. doi: 10.21105/joss.00355 (URL: <a href="https://doi.org/10.21105/joss.00355" class="uri">https://doi.org/10.21105/joss.00355</a>),
&lt;URL: <a href="http://dx.doi.org/10.21105/joss.00355" class="uri">http://dx.doi.org/10.21105/joss.00355</a>&gt;.</p>
<p>Wickham et al., (2019). Welcome to the tidyverse. Journal of Open
Source Software, 4(43), 1686, <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a></p>
<p>R Core Team (2020). R: A language and environment for statistical
computing. R Foundation for Statistical Computing, Vienna, Austria. URL
<a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
<p>Code and data supporting this analysis is available at: “<a href="https://github.com/DanteChen0825/STA304" class="uri">https://github.com/DanteChen0825/STA304</a>”.</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="../../../../index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="../../../../images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="../../../../js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

